### PR TITLE
Fixed French translations and added a Bulgarian one

### PR DESCRIPTION
**Pull request by Bussun**
All is in the title

### CODE REVIEW

**Comment by SuperHackio** [comment]
Can I ask why this was closed?
It seems like something that would've been accepted (though I'd need to check it over to make sure that you didn't break any other languages)

**Comment by Bussun** [comment]
It's just that I wanted to cancel it (I figured out that I can't) to push another commit before resubmitting and I'm not really familiar with git

**Comment by SuperHackio** [comment]
I See
No worries! For future reference, when you are doing a pull request, you can push as many times as you want until the request is accepted, and those new pushes will end up being a part of the pull request as well.

**Comment by Bussun** [comment]
Oh I didn't know, thanks for the info!
I don't know if that was the most appropriate move but I have opened another pr with the last small commit.

**Pull request closed without merging**
